# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tservicepb\"&\n\x15GeneralServiceRequest\x12\r\n\x05query\x18\x01 \x01(\t\"(\n\x16GeneralServiceResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\\\n\x0eGeneralService\x12J\n\x03\x41sk\x12 .servicepb.GeneralServiceRequest\x1a!.servicepb.GeneralServiceResponseB*Z(github.com/ManoVikram/AI-Fine-Tuning/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/ManoVikram/AI-Fine-Tuning/api'
  _globals['_GENERALSERVICEREQUEST']._serialized_start=28
  _globals['_GENERALSERVICEREQUEST']._serialized_end=66
  _globals['_GENERALSERVICERESPONSE']._serialized_start=68
  _globals['_GENERALSERVICERESPONSE']._serialized_end=108
  _globals['_GENERALSERVICE']._serialized_start=110
  _globals['_GENERALSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
