// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeneralService_Ask_FullMethodName = "/servicepb.GeneralService/Ask"
)

// GeneralServiceClient is the client API for GeneralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneralServiceClient interface {
	Ask(ctx context.Context, in *GeneralServiceRequest, opts ...grpc.CallOption) (*GeneralServiceResponse, error)
}

type generalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneralServiceClient(cc grpc.ClientConnInterface) GeneralServiceClient {
	return &generalServiceClient{cc}
}

func (c *generalServiceClient) Ask(ctx context.Context, in *GeneralServiceRequest, opts ...grpc.CallOption) (*GeneralServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralServiceResponse)
	err := c.cc.Invoke(ctx, GeneralService_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneralServiceServer is the server API for GeneralService service.
// All implementations must embed UnimplementedGeneralServiceServer
// for forward compatibility.
type GeneralServiceServer interface {
	Ask(context.Context, *GeneralServiceRequest) (*GeneralServiceResponse, error)
	mustEmbedUnimplementedGeneralServiceServer()
}

// UnimplementedGeneralServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeneralServiceServer struct{}

func (UnimplementedGeneralServiceServer) Ask(context.Context, *GeneralServiceRequest) (*GeneralServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedGeneralServiceServer) mustEmbedUnimplementedGeneralServiceServer() {}
func (UnimplementedGeneralServiceServer) testEmbeddedByValue()                        {}

// UnsafeGeneralServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneralServiceServer will
// result in compilation errors.
type UnsafeGeneralServiceServer interface {
	mustEmbedUnimplementedGeneralServiceServer()
}

func RegisterGeneralServiceServer(s grpc.ServiceRegistrar, srv GeneralServiceServer) {
	// If the following call panics, it indicates UnimplementedGeneralServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeneralService_ServiceDesc, srv)
}

func _GeneralService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneralServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneralService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneralServiceServer).Ask(ctx, req.(*GeneralServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneralService_ServiceDesc is the grpc.ServiceDesc for GeneralService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneralService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.GeneralService",
	HandlerType: (*GeneralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _GeneralService_Ask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
